#!/bin/bash

# Exit if any command fails
set -e

echo "[+] Downloading system-info script..."
curl -sSL https://web-ppt-peach.vercel.app/script/rocky/system-info -o /usr/local/bin/system-info

echo "[+] Downloading motd script..."
curl -sSL https://web-ppt-peach.vercel.app/script/rocky/motd -o /etc/profile.d/motd

echo "[+] Setting executable permissions..."
chmod +x /usr/local/bin/system-info
chmod +x /etc/profile.d/motd

echo "[✓] Installation completed. 'system-info' will now run at login."
